repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/pylint
    rev: 2.17.4
    hooks:
      - id: pylint
        args: [--disable=C0114,C0115,C0116]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

