name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create secrets JSON File
        run: |
          echo '{ "cohere_api_key": "Dummy", "openai_api_key": "Dummy", "starcoder_api_key": "Dummy" }' > secrets.json
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install poetry
        run: pip install poetry==1.4.2

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run black (check)
        run: poetry run black --check .

      - name: Run pytest
        run: poetry run pytest

      - name: Run isort (check)
        run: poetry run isort --check .
